### ISSUE TITLE
full API support for Documentum REST 7.2

### ISSUE THREAD

**Issue by gentlewind** [Enterprise-Content-Management/documentum-rest-client-dotnet#1]

**Comment by gentlewind** [comment]
with code commit 07a7219, all REST 7.2 services are supported now.

**Comment by jonathanrobie** [comment]
Could you please outline the changes made for this bug?

**Comment by gentlewind** [comment]
Newly added functions by this bug fix:

- Get types and type 
- Get relations and relation
- Create relation
- Get relation types and relation type
- Get network locations and network location
- Simple full-text search
- Get batch capabilities
- Create synchronous batch

Newly added demo by this bug fix:
- Search sample
- Types sample
- Format sample
- Batch sample
