### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by fujiiface** [Enterprise-Content-Management/documentum-rest-client-dotnet#4]
Are you currently taking public contributions?  I'm going through some of the code to get a handle on using the RestClient and have noticed some things that are either confusing or could be implemented in a slightly different way.

**Comment by fujiiface** [comment]
Any response from the maintainers about this?

**Comment by fujiiface** [comment]
Thanks for the response @gentlewind.  I just wanted to do some things here and there to avoid code duplication since I'm watching the project now.  The following are some things I noticed could use improvement/consistency as I was going through the code:

1.  Clean up unused `using` statements and sort them
2.  A little more documentation on using the API
3.  Adding a few function overloads
4.  Consistent formatting and variable names
5.  Use `string` instead of `String`, etc. for data types; usage is inconsistent throughout

I also started putting together a basic MVC demo for people at my work using a wrapper object to make the code even easier to consume and a few nights ago I started messing around with a .NET Core conversion of the RestClient project.  I haven't gotten too far with that though.

**Comment by gentlewind** [comment]
Thanks @fujiiface for the good advices. I agree with you for all above comments. As a demo project, we haven't performed strict code analysis yet. These are things to be done for productivity ready if customers use it in products. We will allocate time to fix them. In the meanwhile, I will work with relevant teams to work out a public contribution process to leverage external experts like you to contribute on the projects.

Regarding the .NET Core conversion, we have similar thoughts and internally we have created projects to convert the code to .NET Core/.NET Standard libraries. I think we can discuss on that more later.
