### ISSUE TITLE
RepositoryExec issue

### ISSUE THREAD

**Issue by fujiiface** [Enterprise-Content-Management/documentum-rest-client-dotnet#5]
Hello,
Any help/direction with this is greatly appreciated.  I'll get a couple items out of the way here:
1. Build: 7.2.0000.0081 13 January 2015
2. DFC Version: 7.2.0000.0054

I'm running into issues with the RestClient in the RepositoryExec.cs file any time `ExecuteDQL<t>` is used.  See code lines below for the exact issue:

```
string dqlUri = LinkRelations.FindLinkAsString(this.Links, LinkRelations.DQL.Rel);
string dqlUriWithoutTemplateParams = dqlUri.Substring(0, dqlUri.IndexOf("{"));
```

The problem is that `LinkRelations.FindLinkAsString` returns a repository URI that is derived from the `hreftemplate` link relation and is stripped of the template params and stores it in `dqlUri`.  Then the same operation is tried again outside of the `Linkrelations.FindLinkAsString` function which causes a `Sytem.ArgumentOutOfRangeException.  Length cannot be less than zero.` exception.  I get this any time the `Feed<T> ExecuteDQL<T>(string dql, FeedOptions options)` function is called.

It should also be noted that the MonoReST solution has the same issue when trying to use the REST API in the AspNetWebFormsRestConsumer project.  That project determines compatibility with the REST API by calling the `D2Repository.isD2Rest()` function.  If the `isD2Rest()` function returns `false`, then the site sets labels to red and says the target repository is not a D2 repository.

I'm pretty new to Documentum so some of this is foreign to me but I assume the RestClient project can be used with my version of Documentum since the overview says the 7.2 and 7.3 REST APIs are supported.  I've also been using the RestDotNetFramework.docx documentation and have been able to use the RestClient project to connect and get references to my Repository, a targeted Cabinet.  

What I've been able to do with the RestClient project:

1. Reference the repository
2. Reference a cabinet
3. Reference the first folder within a Cabinet

I can provide code if that will help but I am currently at a standstill with this API and cannot move forward unless this is fixed or my mistake is pointed out so I can work around it.  Any help is greatly appreciated.

Humbly,
Christopher

**Comment by lili6561** [comment]
Hi Christopher,
Thanks for your caught, I updated RepositoryExec.ExecuteDQL to resolve the mistake you pointed out.

**Comment by fujiiface** [comment]
Thanks @lili6561.  This resolved the issue.  I did something similar to work around it but wanted to make sure it didn't serve some other purpose.
