### ISSUE TITLE
Possible RepositoryExec issue

### ISSUE THREAD

**Issue by ghost** [Enterprise-Content-Management/documentum-rest-client-dotnet#6]
Hello,

I was using the `Repository.GetFolderByQualification(string dql, FeedGetOptions)` function and getting null reference exceptions instead of what I expected to be a null Folder object.  After digging through the code some more I found that the function I am using on Line 292 of `RepositoryExec.cs` calls the generic `GetObjectByQualification<T>(string dql, SingleGetOptions options)` function.  This function prepends `select r_object_id from ` to the passed in dql statement which, in my case, resulted in dql like the following: `select r_object_id from select r_object_id, r_folder_path from `.

Is this the expected behavior or should the line on 352 be removed?

Here's the code from `RepositoryExec.cs` with a comment on the line in the code that is causing a problem:
```
/// <summary>
/// Get object by dql qualification
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="dql"></param>
/// <param name="options"></param>
/// <returns></returns>
public T GetObjectByQualification<T>(string dql, SingleGetOptions options)
{
    dql = "select r_object_id from " + dql; //THIS LINE IS CAUSING THE PROBLEM
    Feed<PersistentObject> feed = ExecuteDQL<PersistentObject>(dql, new FeedGetOptions { Inline = false });
    if (feed.Entries == null || feed.Entries.Count == 0)
    {
        return default(T);
    }
    if (feed.Entries.Count > 1)
    {
        throw new Exception("The qualification '" + dql + "' has more than one object in repository.");
    }
    return Client.GetSingleton<T>(feed.Entries[0].Links, LinkRelations.EDIT.Rel, options);
}
```

**Comment by gentlewind** [comment]
This API is not a native REST API but a handy API written on the client side by calling 2 REST APIs. A qualification doesn't let you specify the `select` statement. A valid qualification is like this: `dm_document where r_object_id='0900000000000000'`.
If you want to specify which attributes to be returned, you can set it in parameter `SingleGetOptions ` like `new SingleGetOptions { View = 'r_object_id,r_folder_path'}`.

**Comment by ghost** [comment]
Thanks @gentlewind.  I was able to get this working now using your explanation and converting the `r_folder_path` to a `JArray` object.
